// GENERATED by scripts/gen-artikler.mjs from docs/scrape — do not edit by hand.
import type { Img } from "@/lib/types";

export type ArticleBlock =
  | { type: "heading"; level: 2 | 3 | 4; text: string }
  | { type: "text"; text: string; bold?: boolean; list?: number }
  | { type: "image"; image: Img; caption?: string }
  | { type: "link"; text: string; href: string };

export type Article = {
  id: string;
  title: string;
  /** Live's second H1. Sometimes verbatim identical to `title` (nytt-design) — rendered either way, matching live. */
  subtitle?: string;
  /** No article shows a visible publish date on live (Framer's <time> renders empty) — never set. */
  date?: string;
  /** The article page's own hero image. Differs from `cardImage` (docs/scrape/artikler__<id>.json). */
  hero: Img;
  /** The listing image used by the /artikler index and home page cards (docs/scrape/artikler.json). */
  cardImage: Img;
  body: ArticleBlock[];
  metaTitle: string;
  metaDescription: string;
};

export const artikler: Article[] = [
  {
    "id": "nytt-design",
    "title": "Nytt design på Elbas hjemmeside",
    "subtitle": "Nytt design på Elbas hjemmeside",
    "hero": {
      "src": "/images/artikler__nytt-design/01-95634bec.jpeg",
      "alt": "",
      "width": 512,
      "height": 384
    },
    "cardImage": {
      "src": "/images/home/06-d6adc654.jpeg",
      "alt": "",
      "width": 386,
      "height": 358
    },
    "body": [
      {
        "type": "text",
        "text": "Vi er glade for å lansere en helt ny versjon av ELBAs hjemmeside."
      },
      {
        "type": "text",
        "text": "Nettsiden har fått et moderne design, forbedret struktur og en mer brukervennlig opplevelse – slik at du raskt og enkelt finner informasjonen du trenger."
      },
      {
        "type": "text",
        "text": "Målet med oppdateringen har vært tydelig: gjøre det enklere for kunder og samarbeidspartnere å bli kjent med våre produkter, tjenester og løsninger."
      },
      {
        "type": "text",
        "text": "Mye er gjort, og noe gjenstår."
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Hva er nytt?"
      },
      {
        "type": "heading",
        "level": 3,
        "text": "Enklere navigasjon"
      },
      {
        "type": "text",
        "text": "Vi har reorganiserer innholdet slik at du lettere finner frem til riktig informasjon. Produkter, tjenester og kontaktpunkter blir mer oversiktlige og tilgjengelige."
      },
      {
        "type": "heading",
        "level": 3,
        "text": "Moderne og ryddig design"
      },
      {
        "type": "text",
        "text": "Det nye visuelle uttrykket gjenspeiler ELBAs profesjonalitet og kvalitet. Ren layout, tydelige seksjoner og bedre bruk av bilder gir en mer helhetlig opplevelse."
      },
      {
        "type": "heading",
        "level": 3,
        "text": "Bedre på mobil og nettbrett"
      },
      {
        "type": "text",
        "text": "Nettsiden er fullt responsiv og fungerer sømløst på alle enheter – enten du besøker oss fra mobil, nettbrett eller PC."
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Hvorfor denne oppgraderingen?"
      },
      {
        "type": "text",
        "text": "Vi ønsker at nettsiden skal være et nyttig verktøy for både eksisterende og nye kunder. Den skal gjøre det enklere å:"
      },
      {
        "type": "text",
        "text": "finne riktig produkt eller løsning",
        "list": 0
      },
      {
        "type": "text",
        "text": "sende forespørsler",
        "list": 0
      },
      {
        "type": "text",
        "text": "komme i kontakt med oss",
        "list": 0
      },
      {
        "type": "text",
        "text": "få oversikt over hva Elba tilbyr",
        "list": 0
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Ta en titt"
      },
      {
        "type": "text",
        "text": "Vi inviterer deg til å utforske den nye nettsiden og bli kjent med det oppdaterte designet. Har du tilbakemeldinger eller spørsmål, hører vi gjerne fra deg."
      },
      {
        "type": "text",
        "text": "Velkommen til nye ELBA.no!"
      }
    ],
    "metaTitle": "Nytt design på Elbas hjemmeside — Elba",
    "metaDescription": "ELBA - Din partner innen smøreteknikk i Norge. Fra den minste minigraver til Norges største produksjonsanlegg er vi klare til å møte utfordringen med deg."
  },
  {
    "id": "nytt-eierskap",
    "title": "Nytt eierskap for Elba",
    "subtitle": "Daglig leder kjøper opp Elba sammen med islendinger",
    "hero": {
      "src": "/images/artikler__nytt-eierskap/01-2291d1ce.jpeg",
      "alt": "",
      "width": 512,
      "height": 276
    },
    "cardImage": {
      "src": "/images/home/07-85311014.jpeg",
      "alt": "ELBA X SKRALLI",
      "width": 386,
      "height": 328
    },
    "body": [
      {
        "type": "text",
        "text": "Ronny, daglig leder i Elba, har kjøpt opp selskapet sammen med islendingene i Skralli."
      },
      {
        "type": "text",
        "text": "Elba, en ledende aktør innen smøresystemer og utstyr til anlegg og industri i Norge, har fått nye eiere. Selskapet eies nå av daglig leder Ronny Thoresen, som har vært en del av Elba i nær 30 år, og det islandske selskapet Skralli. KPMG i Norge har vært rådgivere i prosessen."
      },
      {
        "type": "text",
        "text": "Elba har i en årrekke vært spesialist på smøreanlegg i Norge, og med Ronny på eiersiden videreføres kontinuiteten i selskapet."
      },
      {
        "type": "text",
        "text": "“Vi skal bygge videre på det fundamentet som er lagt igjennom flere tiår,” sier Ronny, daglig leder og medeier i Elba."
      },
      {
        "type": "text",
        "text": "Skralli er en sentral aktør innen service til anlegg, industri og landbruk på Island, og er det eneste selskapet der som har smøreanlegg som et av sine kjerneområder. Med de nye eierne får Elba et solid fundament for videre vekst i et marked som i økende grad preges av teknologiutvikling og strengere regelverk. Målet er å møte kundenes behov for mer avansert overvåking og etterlevelse av stadig høyere krav."
      },
      {
        "type": "text",
        "text": "Skralli kommer inn som en strategisk partner, med daglig leder Vilmundur “Villi” Theodorsson i spissen. Villi har lang erfaring fra anleggsbransjen på Island, men er mest kjent i Norge fra sin rolle som senior produktsjef hos Pon Equipment Norge fra 2010 til 2020."
      },
      {
        "type": "text",
        "text": "“Elba og Skralli utfyller hverandre godt. Hos Skralli har vi bygget opp et team med lang bransjeerfaring innen anlegg, landbruk og industri, fra både Norge og Island, så her har vi gode muligheter til å dele erfaring på tvers av selskapene.” sier Villi, daglig leder i Skralli og styreleder i Elba."
      },
      {
        "type": "image",
        "image": {
          "src": "/images/artikler__nytt-eierskap/02-4cbf519c.jpg",
          "alt": "Nye eiere av Elba",
          "width": 1440,
          "height": 1223
        },
        "caption": "Fra venstre, Hlynur Isak Vilmundarson (medeier i Skralli og prosjektleder Elba), Ronny J. Thoresen (daglig leder Elba), Leif Børre Andersen (tidligere eier av Elba), Vilmundur Theodorsson (medeier og daglig leder i Skralli), Örvar S. Haraldsson (medeier og salgssjef i Skralli)"
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Gir stafettpinnen videre"
      },
      {
        "type": "text",
        "text": "Etter mange år ved roret overlater nå tidligere eier Leif Børre Andersen styringen til Ronny og de nye eierne. “Jeg har vært med siden oppstarten i 1991, og det føles riktig å gi stafettpinnen videre til nye eiere som kan føre selskapet videre.\" sier Leif Børre Andersen, som nå går av med pensjon."
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Et startskudd for videre vekst og innovasjon"
      },
      {
        "type": "text",
        "text": "De nye eierne har allerede identifisert flere satsingsområder som skal styrke Elba i årene som kommer. Strengere krav til sertifiseringer og sikkerhet, spesielt fra kunder innen offshore og industri, gjør at kvalitet og sporbarhet blir sentrale temaer fremover."
      },
      {
        "type": "text",
        "text": "“Vi vil bruke mer ressurser på å følge opp kundene våre tettere og tilby enda raskere og mer forutsigbar service”"
      },
      {
        "type": "text",
        "text": "- Ronny, daglig leder"
      },
      {
        "type": "text",
        "text": "En viktig del av satsingen er modernisering og digitalisering av smøresystemene. Elba vil i større grad ta i bruk sensorteknologi og flowmetere som gir bedre overvåkning av anleggene. Slik kan vedlikehold planlegges før feil oppstår, noe som reduserer kostnader og nedetid, og fører til høy driftssikkerhet for kundene."
      }
    ],
    "metaTitle": "Nytt eierskap for Elba — Elba",
    "metaDescription": "ELBA - Din partner innen smøreteknikk i Norge. Fra den minste minigraver til Norges største produksjonsanlegg er vi klare til å møte utfordringen med deg."
  },
  {
    "id": "passiv-og-aktiv-overvaaking",
    "title": "Passiv og aktiv overvåking for driftsledere",
    "subtitle": "Slik gir smart overvåking av smøreanlegg høyere oppetid og lavere kostnader",
    "hero": {
      "src": "/images/home/08-8da04b4f.jpg",
      "alt": "",
      "width": 512,
      "height": 341
    },
    "cardImage": {
      "src": "/images/home/08-8da04b4f.jpg",
      "alt": "Groenevald-BEKA logo",
      "width": 386,
      "height": 257
    },
    "body": [
      {
        "type": "text",
        "text": "For driftsledere i produksjonsanlegg, entreprenørvirksomheter og selskaper med store maskinparker er én ting helt avgjørende: forutsigbar drift. Smøring er ofte en undervurdert faktor – helt til den svikter. Med moderne smøreanlegg som kombinerer digital fjernovervåking og analoge sikkerhetsindikatorer, kan du ta full kontroll på maskinparken, redusere risiko og planlegge vedlikehold smartere."
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Hvorfor smøring er kritisk for driftssikkerhet"
      },
      {
        "type": "text",
        "text": "Mangelfull eller feil smøring er blant de vanligste årsakene til slitasje, varmgang og havari i maskiner. Konsekvensene er kostbare: uplanlagt nedetid, hastetilgang på deler og produksjonstap. For virksomheter med mange maskiner blir manuell oppfølging raskt en flaskehals. Løsningen er automatisert smøring med overvåking."
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Dobbel kontroll: digital og analog overvåking"
      },
      {
        "type": "text",
        "text": "Elba leverer moderene smøreanlegg som gir mulighet for både analog og digital overvåking:"
      },
      {
        "type": "heading",
        "level": 3,
        "text": "Analog overvåking er enkel og robust"
      },
      {
        "type": "text",
        "text": "Visuell indikatorstift på hovedblokk i progressivsystemer viser at smøresyklusen faktisk går.",
        "list": 0
      },
      {
        "type": "text",
        "text": "Overtrykksventiler varsler lokalt dersom et smørepunkt er blokkert.",
        "list": 0
      },
      {
        "type": "text",
        "text": "Fordel: Umiddelbar, visuell bekreftelse ute på maskinen som fungerer alltid, også uten strøm eller nett.",
        "list": 0
      },
      {
        "type": "heading",
        "level": 3,
        "text": "Digital overvåking gir full oversikt, hvor som helst"
      },
      {
        "type": "text",
        "text": "I samarbeid med El-Watch kan smøreanlegget utstyres med trådløse sensorer som:"
      },
      {
        "type": "text",
        "text": "Overvåker trykk, sykluser og status kontinuerlig",
        "list": 1
      },
      {
        "type": "text",
        "text": "Sender sanntidsvarsler ved avvik (e-post/SMS/portal)",
        "list": 1
      },
      {
        "type": "text",
        "text": "Logger historikk og dokumentasjon for analyse og etterprøvbarhet",
        "list": 1
      },
      {
        "type": "text",
        "text": "Gir fjerninnsyn i hele maskinparken på tvers av lokasjoner",
        "list": 1
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Hva betyr dette i praksis for deg som driftsleder?"
      },
      {
        "type": "heading",
        "level": 3,
        "text": "1) Mindre nedetid og mer forutsigbar produksjon"
      },
      {
        "type": "text",
        "text": "Du får varsel før en smørefeil utvikler seg til et havari. Det gir deg handlingsrom til å planlegge tiltak i stedet for å håndtere kriser."
      },
      {
        "type": "heading",
        "level": 3,
        "text": "2) Lavere vedlikeholdskostnader"
      },
      {
        "type": "text",
        "text": "Planlagt vedlikehold er betydelig rimeligere enn akutte stopp. Med data og varsler kan du bytte deler og rense linjer når det faktisk trengs."
      },
      {
        "type": "heading",
        "level": 3,
        "text": "3) Full kontroll på store maskinparker"
      },
      {
        "type": "text",
        "text": "Har du mange maskiner i produksjon, på anlegg eller ute hos kunder, gir fjernovervåking én samlet oversikt. Du slipper tidkrevende manuelle inspeksjoner."
      },
      {
        "type": "heading",
        "level": 3,
        "text": "4) Dokumentasjon og ansvarlighet"
      },
      {
        "type": "text",
        "text": "All smøreaktivitet logges. Det gir verdifull dokumentasjon internt – og er spesielt nyttig for:"
      },
      {
        "type": "text",
        "text": "Maskinutleie (bevis på korrekt drift)",
        "list": 2
      },
      {
        "type": "text",
        "text": "Flere operatører på samme maskin",
        "list": 2
      },
      {
        "type": "text",
        "text": "Revisjoner og kvalitetskrav",
        "list": 2
      },
      {
        "type": "heading",
        "level": 3,
        "text": "5) Enkelt å ta i bruk, også på eksisterende anlegg"
      },
      {
        "type": "text",
        "text": "De trådløse sensorene er raske å montere og krever minimal inngripen. Digital overvåking kan ettermonteres på eksisterende smøresystemer."
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Hvem passer løsningen for?"
      },
      {
        "type": "text",
        "text": "Denne kombinasjonen av analog og digital overvåking er spesielt verdifull for:"
      },
      {
        "type": "text",
        "text": "Produksjonsanlegg med kontinuerlig drift",
        "list": 3
      },
      {
        "type": "text",
        "text": "Store entreprenører med mange maskiner på ulike lokasjoner",
        "list": 3
      },
      {
        "type": "text",
        "text": "Maskinutleie som trenger dokumentasjon og kontroll",
        "list": 3
      },
      {
        "type": "text",
        "text": "Driftsmiljøer med høye krav til oppetid og sikkerhet",
        "bold": true,
        "list": 3
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Fra reaktivt til proaktivt vedlikehold"
      },
      {
        "type": "text",
        "text": "Når smøreanlegget overvåkes kontinuerlig, går du fra å reagere på feil til å forutse dem. Det er kjernen i prediktivt vedlikehold og en av de mest effektive måtene å forbedre både drift og økonomi på."
      }
    ],
    "metaTitle": "Passiv og aktiv overvåking for driftsledere — Elba",
    "metaDescription": "ELBA - Din partner innen smøreteknikk i Norge. Fra den minste minigraver til Norges største produksjonsanlegg er vi klare til å møte utfordringen med deg."
  },
  {
    "id": "hvorfor-smoresystem-industri",
    "title": "Hvordan sparer smøresystemer penger?",
    "subtitle": "Hvordan smøresystemer sparer tid og penger i industrien",
    "hero": {
      "src": "/images/artikler/05-aa3c90a2.png",
      "alt": "Smøresystem",
      "width": 512,
      "height": 384
    },
    "cardImage": {
      "src": "/images/artikler/05-aa3c90a2.png",
      "alt": "Smøresysten",
      "width": 386,
      "height": 290
    },
    "body": [
      {
        "type": "text",
        "text": "I industrien er det ofte de små tingene som avgjør lønnsomheten. Smøring er et godt eksempel. Det blir sjelden snakket høyt om, helt til noe stopper opp. Da blir det plutselig veldig dyrt."
      },
      {
        "type": "text",
        "text": "Med riktige smøresystemer kan industribedrifter redusere nedetid, forlenge levetiden på maskiner og frigjøre verdifull arbeidstid. Resultatet er lavere kostnader, bedre driftssikkerhet og mer forutsigbar produksjon."
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Smøring som en del av produksjonen"
      },
      {
        "type": "text",
        "text": "Manuell smøring krever planlegging, ofte med stopp i produksjonen og personell som fysisk må til maskinen. I praksis betyr dette ofte at smøring blir utsatt, glemt eller utført ujevnt."
      },
      {
        "type": "text",
        "text": "Automatiske og sentraliserte smøresystemer gjør smøring til en kontinuerlig del av driften. Smørepunktene får riktig mengde smøremiddel – til rett tid – mens maskinen er i gang."
      },
      {
        "type": "text",
        "text": "Dette gir:"
      },
      {
        "type": "text",
        "text": "Jevn og korrekt smøring",
        "list": 0
      },
      {
        "type": "text",
        "text": "Mindre slitasje på lager, kjeder og føringer",
        "list": 0
      },
      {
        "type": "text",
        "text": "Færre uforutsette driftsstans",
        "list": 0
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Mindre vedlikehold, færre timer og lavere kostnader"
      },
      {
        "type": "text",
        "text": "Vedlikehold er kostbart, spesielt når det er reaktivt. Slitte komponenter, havarier og hasteutkall gir både direkte kostnader og tapte produksjonstimer."
      },
      {
        "type": "text",
        "text": "Et godt smøresystem:"
      },
      {
        "type": "text",
        "text": "Reduserer behovet for akutte reparasjoner",
        "list": 1
      },
      {
        "type": "text",
        "text": "Forlenger levetiden på kritiske komponenter",
        "list": 1
      },
      {
        "type": "text",
        "text": "Gir mer planlagt og forutsigbart vedlikehold",
        "list": 1
      },
      {
        "type": "text",
        "text": "Mange av våre kunder opplever at investeringen i et smøresystem betaler seg raskt – ofte gjennom færre vedlikeholdstimer alene."
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Frigjør fagfolk til viktigere oppgaver"
      },
      {
        "type": "text",
        "text": "I en tid der kvalifisert personell er en knapp ressurs, gir det liten mening at dyktige teknikere bruker tid på rutinemessig smøring."
      },
      {
        "type": "text",
        "text": "Med automatiske systemer:"
      },
      {
        "type": "text",
        "text": "Brukes færre timer på enkle, manuelle oppgaver",
        "list": 2
      },
      {
        "type": "text",
        "text": "Kan vedlikeholdspersonell fokusere på inspeksjon og forbedring",
        "list": 2
      },
      {
        "type": "text",
        "text": "Blir HMS bedre, fordi færre må inn i utsatte områder",
        "list": 2
      },
      {
        "type": "text",
        "text": "Dette gir både bedre ressursbruk og tryggere arbeidsforhold."
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Smøresystemer kan tilpasses og overtas"
      },
      {
        "type": "text",
        "text": "Mange tror at nye smøresystemer alltid betyr full utskifting. Det stemmer ikke hos Elba."
      },
      {
        "type": "text",
        "text": "Hos Elba jobber vi daglig med:"
      },
      {
        "type": "text",
        "text": "Å ta over og videreutvikle eksisterende smøresystemer",
        "list": 3
      },
      {
        "type": "text",
        "text": "Service og optimalisering, uavhengig av leverandør og løsning",
        "list": 3
      },
      {
        "type": "text",
        "text": "Tilpasning av systemtype etter bruksområde og drift",
        "list": 3
      },
      {
        "type": "text",
        "text": "Enten det er progressive systemer, enlinje-, tolinje- eller flerledersystemer, finnes det løsninger som passer både nye og eldre anlegg."
      },
      {
        "type": "heading",
        "level": 2,
        "text": "En investering i driftssikkerhet"
      },
      {
        "type": "text",
        "text": "Smøring handler ikke bare om fett og olje – det handler om oppetid, kontroll og forutsigbarhet. I industrien er dette verdier som direkte påvirker bunnlinjen."
      },
      {
        "type": "text",
        "text": "Riktig smøresystem er derfor ikke en kostnad, men en investering i:"
      },
      {
        "type": "text",
        "text": "Stabil drift",
        "list": 4
      },
      {
        "type": "text",
        "text": "Lavere totale eierkostnader",
        "list": 4
      },
      {
        "type": "text",
        "text": "Lengre levetid på maskiner og utstyr",
        "list": 4
      },
      {
        "type": "text",
        "text": "Ønsker du å vite hvordan et smøresystem kan optimaliseres for din drift, tar vi gjerne en prat."
      }
    ],
    "metaTitle": "Hvordan sparer smøresystemer penger? — Elba",
    "metaDescription": "ELBA - Din partner innen smøreteknikk i Norge. Fra den minste minigraver til Norges største produksjonsanlegg er vi klare til å møte utfordringen med deg."
  },
  {
    "id": "velge-system",
    "title": "Å velge riktig type system",
    "subtitle": "Hvordan velge riktig smøresystem for din drift?",
    "hero": {
      "src": "/images/artikler__velge-system/01-f8b4ac80.jpeg",
      "alt": "",
      "width": 512,
      "height": 683
    },
    "cardImage": {
      "src": "/images/artikler/06-a2ff5186.jpeg",
      "alt": "",
      "width": 515,
      "height": 687
    },
    "body": [
      {
        "type": "text",
        "text": "Valg av riktig smøresystem er avgjørende for driftssikkerhet, vedlikeholdskostnader og levetid på maskiner. For driftsledere i produksjonsanlegg, entreprenørvirksomheter og selskaper med store maskinparker finnes det ikke én løsning som passer alle. Riktig system avhenger av maskintype, antall smørepunkter og driftsforhold."
      },
      {
        "type": "text",
        "text": "Her er en kort og praktisk gjennomgang av de vanligste typene smøresystemer og når de passer best."
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Enlinjesystem (single-line)"
      },
      {
        "type": "text",
        "text": "Best egnet for: Mindre og mellomstore systemer, moderate avstander og stabile forhold."
      },
      {
        "type": "text",
        "text": "Én hovedlinje som forsyner alle smørepunkter",
        "list": 0
      },
      {
        "type": "text",
        "text": "Enkel oppbygning og kostnadseffektiv løsning",
        "list": 0
      },
      {
        "type": "text",
        "text": "Lett å installere og vedlikeholde",
        "list": 0
      },
      {
        "type": "text",
        "text": "Styrker:",
        "bold": true
      },
      {
        "type": "text",
        "text": "Driftssikkert og oversiktlig",
        "list": 1
      },
      {
        "type": "text",
        "text": "God løsning der belastning og temperatur er relativt stabile",
        "list": 1
      },
      {
        "type": "text",
        "text": "Begrensninger:",
        "bold": true
      },
      {
        "type": "text",
        "text": "Mindre egnet for svært store systemer eller lange avstander",
        "list": 2
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Tolinjesystem (dual-line)"
      },
      {
        "type": "text",
        "text": "Best egnet for: Store anlegg, tung industri og krevende miljøer."
      },
      {
        "type": "text",
        "text": "To hovedlinjer som jobber vekselvis",
        "list": 3
      },
      {
        "type": "text",
        "text": "Kan håndtere høyt trykk og lange rørstrekk",
        "list": 3
      },
      {
        "type": "text",
        "text": "Svært robust løsning",
        "list": 3
      },
      {
        "type": "text",
        "text": "Styrker:",
        "bold": true
      },
      {
        "type": "text",
        "text": "Ideell for mange smørepunkter",
        "list": 4
      },
      {
        "type": "text",
        "text": "Tåler tøffe forhold og varierende belastning",
        "list": 4
      },
      {
        "type": "text",
        "text": "Begrensninger:",
        "bold": true
      },
      {
        "type": "text",
        "text": "Mer kompleks installasjon",
        "list": 5
      },
      {
        "type": "text",
        "text": "Høyere investeringskostnad enn enlinje",
        "list": 5
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Progressivt system"
      },
      {
        "type": "text",
        "text": "Best egnet for: Maskiner og anlegg der kontroll og driftssikkerhet er kritisk."
      },
      {
        "type": "text",
        "text": "Smøringen går i en fast rekkefølge gjennom fordelere",
        "list": 6
      },
      {
        "type": "text",
        "text": "Hvis ett punkt blokkeres, stopper hele systemet, noe som gjør feil lett å oppdage",
        "list": 6
      },
      {
        "type": "text",
        "text": "Styrker:",
        "bold": true
      },
      {
        "type": "text",
        "text": "Høy presisjon og kontroll",
        "list": 7
      },
      {
        "type": "text",
        "text": "Enkelt å overvåke både mekanisk og digitalt",
        "list": 7
      },
      {
        "type": "text",
        "text": "Svært populært i entreprenør- og industrimaskiner",
        "list": 7
      },
      {
        "type": "text",
        "text": "Begrensninger:",
        "bold": true
      },
      {
        "type": "text",
        "text": "Mindre egnet der ekstrem fleksibilitet kreves",
        "list": 8
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Flerlinjesystem (multi-line)"
      },
      {
        "type": "text",
        "text": "Best egnet for: Mindre maskiner med få smørepunkter eller der fleksibilitet er viktig."
      },
      {
        "type": "text",
        "text": "Hver smørelinje går direkte fra pumpen til smørepunktet",
        "list": 9
      },
      {
        "type": "text",
        "text": "Full uavhengighet mellom punktene",
        "list": 9
      },
      {
        "type": "text",
        "text": "Styrker:",
        "bold": true
      },
      {
        "type": "text",
        "text": "Svært fleksibelt",
        "list": 10
      },
      {
        "type": "text",
        "text": "Enkelt å justere individuelle smøremengder",
        "list": 10
      },
      {
        "type": "text",
        "text": "Begrensninger:",
        "bold": true
      },
      {
        "type": "text",
        "text": "Begrenset antall smørepunkter",
        "list": 11
      },
      {
        "type": "text",
        "text": "Mindre egnet for store systemer",
        "list": 11
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Hvilket system bør du velge?"
      },
      {
        "type": "text",
        "text": "Som tommelfingerregel:"
      },
      {
        "type": "text",
        "text": "Få smørepunkter / enkel maskin: Flerlinje eller enlinje",
        "list": 12
      },
      {
        "type": "text",
        "text": "Mange smørepunkter / høy driftssikkerhet: Progressivt system",
        "list": 12
      },
      {
        "type": "text",
        "text": "Store anlegg / lange avstander / tung industri: Tolinjesystem",
        "list": 12
      },
      {
        "type": "text",
        "text": "Riktig valg handler ikke bare om teknikk men om driftsmønster, vedlikeholdsstrategi og krav til oppetid."
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Overvåking: fra enkel visuell kontroll til full fjernovervåking"
      },
      {
        "type": "text",
        "text": "Uansett type smøresystem kan Elba levere løsninger med ulike nivåer av overvåking:"
      },
      {
        "type": "heading",
        "level": 4,
        "text": "Analog overvåking:"
      },
      {
        "type": "text",
        "text": "Visuelle indikatorstifter og overtrykksventiler gir rask lokal kontroll."
      },
      {
        "type": "heading",
        "level": 4,
        "text": "Digital overvåking:"
      },
      {
        "type": "text",
        "text": "I samarbeid med El-Watch kan smøreanlegg overvåkes trådløst med sensorer som gir:"
      },
      {
        "type": "text",
        "text": "Sanntidsvarsler ved avvik",
        "list": 13
      },
      {
        "type": "text",
        "text": "Fjerninnsyn i maskinparkens status",
        "list": 13
      },
      {
        "type": "text",
        "text": "Historikk og dokumentasjon for vedlikehold",
        "list": 13
      },
      {
        "type": "text",
        "text": "Dette gir deg mulighet til å gå fra reaktivt til proaktivt vedlikehold og redusere risikoen for uplanlagt nedetid."
      },
      {
        "type": "heading",
        "level": 3,
        "text": "Usikker på hva som passer din drift?"
      },
      {
        "type": "text",
        "text": "Elba hjelper deg med å kartlegge behov, velge riktig smøresystem og sette opp ønsket nivå av overvåking, tilpasset din maskinpark og dine driftsmål."
      }
    ],
    "metaTitle": "Å velge riktig type system — Elba",
    "metaDescription": "ELBA - Din partner innen smøreteknikk i Norge. Fra den minste minigraver til Norges største produksjonsanlegg er vi klare til å møte utfordringen med deg."
  }
];

export const articleBySlug = (slug: string): Article | undefined => artikler.find((a) => a.id === slug);
