// GENERATED by scripts/gen-produkter.mjs from docs/scrape — do not edit by hand.
import type { Img } from "@/lib/types";

export type ProductTable = { heading: string | null; headers: string[]; rows: string[][]; images: Img[] };
export type Product = {
  id: string;
  /** Reserved for the later Zirius (ERP) integration; unset today. */
  erpId?: string;
  title: string;
  hero: Img;
  /** Static sub-navigation pills (not links on the live site) above the tables. Empty on routes without them. */
  subnav: string[];
  intro: string[];
  tables: ProductTable[];
  metaTitle: string;
  metaDescription: string;
};

export const produkter: Product[] = [
  {
    "id": "banjokoblinger",
    "title": "Banjokoblinger",
    "hero": {
      "src": "/images/produkter/10-948804a8.jpg",
      "alt": "",
      "width": 1440,
      "height": 933
    },
    "subnav": [
      "Banjokobling",
      "Banjokobling utv./innv.",
      "Banjo T",
      "Svivel union vinkel",
      "Svivel 90 grader"
    ],
    "intro": [],
    "tables": [
      {
        "heading": null,
        "headers": [
          "D",
          "G",
          "SW",
          "SW1",
          "Serie",
          "Art.Nr."
        ],
        "rows": [
          [
            "4",
            "8x1",
            "10",
            "14",
            "LL",
            "04013210706"
          ],
          [
            "4",
            "10x1",
            "10",
            "14",
            "LL",
            "04013210206"
          ],
          [
            "4",
            "1/8 BSP",
            "10",
            "14",
            "LL",
            "953149559"
          ],
          [
            "6",
            "8x1",
            "12",
            "14",
            "LL",
            "04013200706"
          ],
          [
            "6",
            "10x1",
            "12",
            "14",
            "LL",
            "04013200206LL"
          ],
          [
            "6",
            "10x1",
            "14",
            "14",
            "L",
            "04013200206"
          ],
          [
            "6",
            "1/8 BSP",
            "12",
            "14",
            "LL",
            "04013200906"
          ],
          [
            "6",
            "1/8 BSP",
            "14",
            "14",
            "L",
            "04013200206"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__banjokoblinger/02-164d85ca.png",
            "alt": "",
            "width": 400,
            "height": 260
          },
          {
            "src": "/images/produkter__banjokoblinger/03-a95df89c.png",
            "alt": "",
            "width": 400,
            "height": 260
          }
        ]
      }
    ],
    "metaTitle": "ELBA - I INDUSTRIENS TJENESTE",
    "metaDescription": "ELBA - Din partner innen smøreteknikk i Norge. Fra den minste minigraver til Norges største produksjonsanlegg er vi klare til å møte utfordringen med deg."
  },
  {
    "id": "fett",
    "title": "Fett",
    "hero": {
      "src": "/images/produkter/03-e1cf3aba.jpeg",
      "alt": "",
      "width": 1439,
      "height": 1919
    },
    "subnav": [],
    "intro": [],
    "tables": [
      {
        "heading": null,
        "headers": [
          "Forpakning",
          "NLGI",
          "Fortykker",
          "Tilsats",
          "Belastning",
          "Tilkobling",
          "Temp",
          "Art.Nr."
        ],
        "rows": [
          [
            "400 g patron",
            "EP 2",
            "Calsium",
            "",
            "Svært høy",
            "std",
            "-30 til 120",
            "953148103"
          ],
          [
            "400 g patron",
            "EP 2",
            "Litium",
            "",
            "Medium",
            "std",
            "-30 til 120",
            "953147981"
          ],
          [
            "400 g patron",
            "EP 2",
            "Litium",
            "",
            "Medium",
            "skru",
            "-30 til 150",
            "0320092"
          ],
          [
            "400 g patron",
            "EP 2",
            "Aluminium",
            "Fast",
            "Svært høy",
            "skru",
            "-20 til 1100",
            "0320254"
          ],
          [
            "18 kg spann",
            "EP 2",
            "Calsium",
            "",
            "Høy",
            "",
            "-30 til 120",
            "953146425"
          ],
          [
            "18 kg spann",
            "EP 2",
            "Litium",
            "",
            "Medium",
            "",
            "-30 til 120",
            "953146467"
          ],
          [
            "18 kg spann",
            "EP 2 Bio",
            "Calsium",
            "",
            "Medium",
            "",
            "-30 til 120",
            "953148319"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__fett/02-965997c1.jpeg",
            "alt": "",
            "width": 1200,
            "height": 741
          }
        ]
      }
    ],
    "metaTitle": "ELBA - I INDUSTRIENS TJENESTE",
    "metaDescription": "ELBA - Din partner innen smøreteknikk i Norge. Fra den minste minigraver til Norges største produksjonsanlegg er vi klare til å møte utfordringen med deg."
  },
  {
    "id": "forlengere",
    "title": "Forlengere",
    "hero": {
      "src": "/images/produkter/05-a9bab172.jpg",
      "alt": "",
      "width": 400,
      "height": 266
    },
    "subnav": [
      "Forlenger rett",
      "Forlenger 90 grader",
      "Forlenger 45 grader"
    ],
    "intro": [],
    "tables": [
      {
        "heading": "Forsinket stål (Zn-Ni)",
        "headers": [
          "G",
          "G1",
          "L",
          "L1",
          "SW",
          "Art.Nr."
        ],
        "rows": [
          [
            "M6 x 1",
            "M6 x 1",
            "57.5",
            "7.5",
            "9",
            "953148050"
          ],
          [
            "M6 x 1",
            "M6 x 1",
            "20",
            "7.5",
            "9",
            "953148257"
          ],
          [
            "M6 x 1",
            "M8 x 1",
            "19",
            "7",
            "11",
            "10021000301K"
          ],
          [
            "M6 x 1",
            "M8 x 1",
            "35",
            "23",
            "10",
            "04011605806"
          ],
          [
            "M6 x 1",
            "M10 x 1",
            "23",
            "10",
            "13",
            "04011600506"
          ],
          [
            "M6 x 1",
            "Rp 1/8\" BSP",
            "23",
            "10",
            "13",
            "på forespørsel"
          ],
          [
            "M8 x 1",
            "M8 x 1",
            "18",
            "8",
            "11",
            "10021000304K"
          ],
          [
            "M8 x 1.25",
            "M8 x 1.25",
            "20",
            "7",
            "11",
            "på forespørsel"
          ],
          [
            "M8 x 1",
            "M8 x 1",
            "32",
            "22",
            "11",
            "04011600806"
          ],
          [
            "M8 x 1.25",
            "M8 x 1.25",
            "32",
            "22",
            "11",
            "på forespørsel"
          ],
          [
            "M8 x 1",
            "M8 x 1",
            "62.5",
            "52.5",
            "11",
            "04011603106"
          ],
          [
            "M8 x 1",
            "M10 x 1",
            "23",
            "12",
            "13",
            "04011600106"
          ],
          [
            "M8 x 1",
            "Rp 1/8\" BSP",
            "23",
            "12",
            "13",
            "953148297"
          ],
          [
            "M8 x 1",
            "Rp 1/4\" BSP",
            "22",
            "8",
            "17",
            "953148088"
          ],
          [
            "M10 x 1",
            "M8 x 1",
            "18",
            "8",
            "11",
            "10021000306k"
          ],
          [
            "M10 x 1",
            "M10 x 1",
            "18",
            "7",
            "13",
            "04011610306"
          ],
          [
            "M10 x 1",
            "M10x1",
            "23",
            "12",
            "13",
            "04011600206"
          ],
          [
            "M10 x 1.5",
            "M10x1",
            "23",
            "12",
            "13",
            "på forespørsel"
          ],
          [
            "M10 x 1",
            "M10x1",
            "35",
            "24",
            "13",
            "04011600706"
          ],
          [
            "M10 x 1",
            "M10x1",
            "40",
            "29",
            "13",
            "på forespørsel"
          ],
          [
            "M10 x 1",
            "M10x1",
            "40",
            "9",
            "14",
            "på forespørsel"
          ],
          [
            "M10 x 1",
            "M10x1",
            "50",
            "39",
            "13",
            "04011600606"
          ],
          [
            "M10 x 1",
            "Rp 1/8\" BSP",
            "18",
            "7",
            "13",
            "953149156"
          ],
          [
            "M10 x 1",
            "Rp 1/4\" BSP",
            "22",
            "8",
            "17",
            "953148279"
          ],
          [
            "M12 x 1",
            "M10x1",
            "21",
            "8.5",
            "13",
            "04011610106"
          ],
          [
            "R 1/8\" BSP",
            "M8x1",
            "18",
            "7",
            "13",
            "953148663"
          ],
          [
            "R 1/8\" BSP",
            "M10x1",
            "18",
            "7",
            "13",
            "04011600306"
          ],
          [
            "R 1/8\" BSP",
            "M10x1",
            "50",
            "38",
            "13",
            "04011611506"
          ],
          [
            "R 1/8\" BSP",
            "Rp 1/8\" BSP",
            "18",
            "11",
            "13",
            "953146847"
          ],
          [
            "R 1/8\" BSP",
            "Rp 1/8\" BSP",
            "23",
            "12",
            "13",
            "04011604106"
          ],
          [
            "R 1/8\" BSP",
            "Rp 1/8\" BSP",
            "27",
            "10",
            "15",
            "7158-02"
          ],
          [
            "R 1/8\" BSP",
            "Rp 1/8\" BSP",
            "35",
            "23",
            "13",
            "953146845"
          ],
          [
            "R 1/8\" BSP",
            "Rp 1/8\" BSP",
            "41",
            "29",
            "13",
            "på forespørsel"
          ],
          [
            "R 1/8\" BSP",
            "Rp 1/8\" BSP",
            "45",
            "33",
            "13",
            "953147988"
          ],
          [
            "R 1/8\" BSP",
            "Rp 1/8\" BSP",
            "50",
            "38",
            "13",
            "105225"
          ],
          [
            "R 1/8\" BSP",
            "Rp 1/8\" BSP",
            "60",
            "38",
            "13",
            "105226"
          ],
          [
            "R 1/8\" BSP",
            "Rp 1/4\" BSP",
            "29",
            "10",
            "19",
            "7005-04-02"
          ],
          [
            "R 1/4\" BSP",
            "M10x1",
            "20",
            "9",
            "17",
            "04011601206"
          ],
          [
            "R 1/4\" BSP",
            "M10x1",
            "35",
            "23",
            "14",
            "04011601006"
          ],
          [
            "R 1/4\" BSP",
            "M10x1",
            "55",
            "43",
            "14",
            "04011601106"
          ],
          [
            "R 1/4\" BSP",
            "Rp 1/8\" BSP",
            "20",
            "9",
            "17",
            "12650480"
          ],
          [
            "R 1/8\" BSP",
            "Rp 1/4\" BSP",
            "22",
            "8",
            "17",
            "på forespørsel"
          ],
          [
            "R 1/4\" BSP",
            "Rp 3/8\" BSP",
            "33",
            "9",
            "2",
            "3158-06-04"
          ],
          [
            "R 1/4\" BSP",
            "Rp 1/4\" BSP",
            "25",
            "9",
            "19",
            "på forespørsel"
          ],
          [
            "R 1/4\" BSP",
            "Rp 1/4\" BSP",
            "50",
            "36",
            "17",
            "på forespørsel"
          ],
          [
            "R 1/4\" BSP",
            "Rp 1/4\" BSP",
            "65",
            "51",
            "17",
            "på forespørsel"
          ],
          [
            "R 1/4\" BSP",
            "Rp 1/4\" BSP",
            "85",
            "71",
            "17",
            "på forespørsel"
          ],
          [
            "R 1/4\" BSP",
            "Rp 1/4\" BSP",
            "104",
            "90",
            "17",
            "på forespørsel"
          ],
          [
            "R 1/2\" BSP",
            "Rp 1/4\" BSP",
            "31",
            "10",
            "27",
            "953148017"
          ],
          [
            "1/2\" NPT",
            "1/8\" NPT",
            "31",
            "8",
            "25",
            "RBRN2N8"
          ],
          [
            "1/2\" NPT",
            "1/4\" NPT",
            "34",
            "10",
            "25",
            "953147186"
          ],
          [
            "1/8\" NPT",
            "1/8\" NPT",
            "20",
            "9",
            "43862",
            "på forespørsel"
          ],
          [
            "1/8\" NPT",
            "1/8\" NPT",
            "30",
            "18",
            "43862",
            "på forespørsel"
          ],
          [
            "1/8\" NPT",
            "1/8\" NPT",
            "48",
            "36",
            "42614",
            "på forespørsel"
          ],
          [
            "1/4\"-28 UNF",
            "Rp 1/8\" BSP",
            "23",
            "12",
            "43862",
            "på forespørsel"
          ],
          [
            "1/4\"-28 UNF",
            "M10 x 1",
            "24",
            "6",
            "13",
            "04011601406"
          ],
          [
            "1/4\"-32 UNEF",
            "M10 x 1",
            "24",
            "6",
            "13",
            "04011601306"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__forlengere/02-096291f6.png",
            "alt": "",
            "width": 400,
            "height": 260
          },
          {
            "src": "/images/produkter__forlengere/03-78b5f32a.png",
            "alt": "",
            "width": 400,
            "height": 259
          }
        ]
      },
      {
        "heading": "Syrefast (316 / V4A)",
        "headers": [
          "G",
          "G1",
          "L",
          "L1",
          "SW",
          "Art.Nr."
        ],
        "rows": [
          [
            "M 8 x 1",
            "Rp 1/8 BSP",
            "23",
            "10",
            "13",
            "953149386"
          ],
          [
            "M 10 x 1",
            "M 10 x 1",
            "18",
            "7",
            "13",
            "på forespørsel"
          ],
          [
            "M 10 x 1",
            "M 10 x 1",
            "23",
            "12",
            "13",
            "04011600213"
          ],
          [
            "M 10 x 1",
            "Rp 1/8 BSP",
            "23",
            "12",
            "13",
            "på forespørsel"
          ],
          [
            "M 10 x 1",
            "M 10 x 1",
            "35",
            "24",
            "13",
            "04011610813"
          ],
          [
            "M 10 x 1",
            "M 10 x 1",
            "50",
            "39",
            "13",
            "953149387"
          ],
          [
            "R 1/8 BSP",
            "M 10x1",
            "18",
            "7",
            "13",
            "04011600313"
          ],
          [
            "R 1/8 BSP",
            "Rp 1/8 BSP",
            "18",
            "7",
            "11",
            "på forespørsel"
          ],
          [
            "R 1/8 BSP",
            "Rp 1/8 BSP",
            "23",
            "12",
            "13",
            "04011600313"
          ],
          [
            "R 1/8 BSP",
            "Rp 1/8 BSP",
            "35",
            "23",
            "13",
            "på forespørsel"
          ],
          [
            "R 1/8 BSP",
            "Rp 1/8 BSP",
            "50",
            "38",
            "13",
            "953149388"
          ],
          [
            "R 1/4 BSP",
            "M 10x1",
            "26",
            "14",
            "14",
            "04011601213"
          ],
          [
            "R 1/4 BSP",
            "M 10x1",
            "35",
            "23",
            "14",
            "04011601013"
          ],
          [
            "R 1/4 BSP",
            "M 10x1",
            "55",
            "43",
            "14",
            "04011601113"
          ]
        ],
        "images": []
      },
      {
        "heading": "Messing",
        "headers": [
          "G",
          "G1",
          "L",
          "L1",
          "SW",
          "Art.Nr."
        ],
        "rows": [
          [
            "M 14 x x1",
            "R 1/4 BSP",
            "25",
            "9",
            "19",
            "F2185/57-00"
          ],
          [
            "M 14 x x1",
            "M 22 x 1.5",
            "31",
            "11",
            "27",
            "953148344"
          ],
          [
            "M 18 X 1",
            "M 20 X 1.5",
            "45",
            "",
            "27",
            "953147875"
          ],
          [
            "M 18 X 1",
            "M 20 X 1.5",
            "55",
            "17",
            "27",
            "953147152"
          ],
          [
            "M 18 X 1",
            "M 20 X 1.5",
            "75",
            "17",
            "27",
            "953148014"
          ],
          [
            "M 18 X 1",
            "R 3/8 BSP",
            "",
            "",
            "27",
            "953148417"
          ],
          [
            "M 20 x 1.5",
            "R 1/2 BSP",
            "40",
            "15",
            "27",
            "953147686"
          ],
          [
            "M 20 x 1.5",
            "M 22 x 1.5",
            "",
            "",
            "27",
            "953148295"
          ],
          [
            "M 22 x 1.5",
            "M 20 x 1.5",
            "",
            "",
            "27",
            "953148771"
          ],
          [
            "M 22 x 1.5",
            "R 1/4 BSP",
            "40",
            "15",
            "27",
            "953148176"
          ],
          [
            "R 1/4 BSP",
            "Rp 1/8 BSP",
            "13",
            "8",
            "12",
            "953148083"
          ],
          [
            "7/16-UNEF-28",
            "Rp 1/8 BSP",
            "31",
            "19",
            "16",
            "114048"
          ],
          [
            "7/16-20 JIC",
            "Rp 1/8 BSP",
            "31",
            "19",
            "16",
            "953147721"
          ],
          [
            "UNF 1/4\" - 28",
            "Rp 1/4\" BSP",
            "",
            "",
            "",
            "953147730"
          ],
          [
            "UNF 3/8\"-24",
            "R 1/8\" BSP",
            "30",
            "",
            "",
            "953146632"
          ],
          [
            "UNF 3/4\"-16",
            "M 20 x 1.5",
            "",
            "",
            "",
            "953149523"
          ]
        ],
        "images": []
      }
    ],
    "metaTitle": "ELBA - I INDUSTRIENS TJENESTE",
    "metaDescription": "ELBA - Din partner innen smøreteknikk i Norge. Fra den minste minigraver til Norges største produksjonsanlegg er vi klare til å møte utfordringen med deg."
  },
  {
    "id": "fyllenippler",
    "title": "Fyllenippler",
    "hero": {
      "src": "/images/produkter/13-a8093807.jpg",
      "alt": "",
      "width": 400,
      "height": 261
    },
    "subnav": [
      "Fyllenippel for stuss",
      "Fyllenippel gjenget tilkobling",
      "Fyllenippel overgang"
    ],
    "intro": [],
    "tables": [
      {
        "heading": "Fyllenippel rett",
        "headers": [
          "G",
          "D",
          "SW",
          "L",
          "Art.Nr.",
          "Passer"
        ],
        "rows": [
          [
            "M18 x 1.0",
            "34",
            "32",
            "100",
            "953147153",
            "Groeneveld"
          ],
          [
            "M18 x 1.0",
            "34",
            "32",
            "120",
            "953147153",
            "Groeneveld"
          ],
          [
            "M20 x 1.5",
            "34",
            "32",
            "45",
            "21520150",
            "Beka/Vogel/CLS"
          ],
          [
            "M20 x 1.5",
            "34",
            "32",
            "45",
            "21520152",
            "m/tilbakeslagsventil"
          ],
          [
            "M22 x 1.5",
            "34",
            "32",
            "45",
            "40154",
            "Lincoln-Skf"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__fyllenippler/02-f24eda9f.png",
            "alt": "",
            "width": 400,
            "height": 260
          },
          {
            "src": "/images/produkter__fyllenippler/03-9e68b64a.png",
            "alt": "",
            "width": 400,
            "height": 261
          }
        ]
      },
      {
        "heading": "Fyllenippel 45°",
        "headers": [
          "G",
          "D",
          "SW",
          "L",
          "Art.Nr.",
          "Passer"
        ],
        "rows": [
          [
            "M20 x 1.5",
            "34",
            "32",
            "118",
            "21520146",
            "Beka/Vogel/CLS"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__fyllenippler/02-f24eda9f.png",
            "alt": "",
            "width": 400,
            "height": 260
          },
          {
            "src": "/images/produkter__fyllenippler/05-d9e2c081.png",
            "alt": "",
            "width": 158,
            "height": 103
          }
        ]
      },
      {
        "heading": "Fyllenippel 90°",
        "headers": [
          "G",
          "D",
          "SW",
          "L",
          "Art.Nr.",
          "Passer"
        ],
        "rows": [
          [
            "M18 x 1.0",
            "34",
            "32",
            "100",
            "953147876",
            "Groeneveld"
          ],
          [
            "M20 x 1.5",
            "38",
            "30",
            "50-56",
            "21520149",
            "Beka/Vogel/CLS"
          ],
          [
            "M20 x 1.5",
            "38",
            "30",
            "85-91",
            "21520147",
            "Beka/Vogel/CLS"
          ],
          [
            "M22 x 1.5",
            "34",
            "32",
            "45",
            "40154",
            "Lincoln-Skf"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__fyllenippler/02-f24eda9f.png",
            "alt": "",
            "width": 400,
            "height": 260
          },
          {
            "src": "/images/produkter__fyllenippler/07-a2fcde43.png",
            "alt": "",
            "width": 287,
            "height": 166
          }
        ]
      },
      {
        "heading": "Fyllenippel 0° - 90° justerbar",
        "headers": [
          "G",
          "D",
          "SW",
          "L",
          "Art.Nr.",
          "Passer"
        ],
        "rows": [
          [
            "M20 x 1.5",
            "34",
            "32",
            "145 - 80",
            "10132444",
            "Beka/Vogel/CLS"
          ],
          [
            "M20 x 1.5",
            "34",
            "32",
            "145 - 80",
            "10136837",
            "m/tilbakeslagsventil"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__fyllenippler/08-bc1caf3d.png",
            "alt": "",
            "width": 158,
            "height": 211
          },
          {
            "src": "/images/produkter__fyllenippler/09-175ec288.png",
            "alt": "",
            "width": 158,
            "height": 211
          }
        ]
      }
    ],
    "metaTitle": "ELBA - I INDUSTRIENS TJENESTE",
    "metaDescription": "ELBA - Din partner innen smøreteknikk i Norge. Fra den minste minigraver til Norges største produksjonsanlegg er vi klare til å møte utfordringen med deg."
  },
  {
    "id": "fylleutstyr",
    "title": "Fylleutstyr",
    "hero": {
      "src": "/images/produkter/09-d1bc0ce1.jpeg",
      "alt": "",
      "width": 1440,
      "height": 1440
    },
    "subnav": [
      "Fyllepresse",
      "Fyllepumpe",
      "Holdere"
    ],
    "intro": [
      "Fyllepresse til sentralsmøreanlegg for fettpatron iht. DIN 1284"
    ],
    "tables": [
      {
        "heading": null,
        "headers": [
          "Patron",
          "Tilkobling",
          "L",
          "D",
          "D1",
          "Art.Nr."
        ],
        "rows": [
          [
            "400 g",
            "med tutt og M26 x 1.5",
            "293 mm",
            "54 mm",
            "56 mm",
            "208103026"
          ],
          [
            "400 g",
            "M26 x 1.5",
            "293 mm",
            "54 mm",
            "56 mm",
            "953146912"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__fylleutstyr/02-ee9402bd.png",
            "alt": "",
            "width": 400,
            "height": 260
          },
          {
            "src": "/images/produkter__fylleutstyr/03-8149cfd1.png",
            "alt": "",
            "width": 400,
            "height": 260
          },
          {
            "src": "/images/produkter__fylleutstyr/04-1e0b42a4.png",
            "alt": "",
            "width": 400,
            "height": 260
          },
          {
            "src": "/images/produkter__fylleutstyr/05-06de2523.png",
            "alt": "",
            "width": 400,
            "height": 262
          }
        ]
      },
      {
        "heading": null,
        "headers": [
          "Patron",
          "Tilkobling",
          "L",
          "D",
          "D1",
          "Art.Nr."
        ],
        "rows": [
          [
            "400 g",
            "med tutt",
            "450 mm",
            "54 mm",
            "169 mm",
            "20830001"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__fylleutstyr/06-ebeeb7b4.png",
            "alt": "",
            "width": 362,
            "height": 368
          }
        ]
      }
    ],
    "metaTitle": "ELBA - I INDUSTRIENS TJENESTE",
    "metaDescription": "ELBA - Din partner innen smøreteknikk i Norge. Fra den minste minigraver til Norges største produksjonsanlegg er vi klare til å møte utfordringen med deg."
  },
  {
    "id": "lynfittings",
    "title": "Lynfittings",
    "hero": {
      "src": "/images/produkter/12-f7bc3daa.jpg",
      "alt": "",
      "width": 400,
      "height": 261
    },
    "subnav": [
      "Rett \"GE\"",
      "90° \"WE\"",
      "90° \"WE\" dreibar",
      "Sammenkobling \"G\""
    ],
    "intro": [],
    "tables": [
      {
        "heading": "Lynfittings 0° rett \"GE\"",
        "headers": [
          "D",
          "G",
          "SW",
          "Art.Nr."
        ],
        "rows": [
          [
            "4",
            "M 6 x 1 tap",
            "10",
            "953147893"
          ],
          [
            "4",
            "M 8 x 1 tap",
            "10",
            "04062323"
          ],
          [
            "4",
            "M 10 x 1",
            "11",
            "04060872"
          ],
          [
            "4",
            "R 1/8 BSP",
            "10",
            "105335"
          ],
          [
            "4",
            "1/8 NPT",
            "11",
            "953149567"
          ],
          [
            "4",
            "1/4 - 28 UNF",
            "11",
            "953149566"
          ],
          [
            "6",
            "M 6 x 1",
            "12",
            "953146770"
          ],
          [
            "6",
            "M 8 x 1",
            "12",
            "04060877"
          ],
          [
            "6",
            "M 10 x 1",
            "12",
            "04060876"
          ],
          [
            "6",
            "R 1/8 BSP",
            "12",
            "106033"
          ],
          [
            "6",
            "1/8 NPT",
            "12",
            "953149568"
          ],
          [
            "6",
            "1/4 - 28 UNF",
            "12",
            "953149569"
          ],
          [
            "1/4\"",
            "1/4 - 28 UNF",
            "12",
            "953149570"
          ],
          [
            "1/4\"",
            "1/8 NPT",
            "12",
            "953159571"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__lynfittings/02-1fef0363.png",
            "alt": "",
            "width": 400,
            "height": 260
          },
          {
            "src": "/images/produkter__lynfittings/03-c4fc2c5e.png",
            "alt": "",
            "width": 400,
            "height": 263
          }
        ]
      }
    ],
    "metaTitle": "ELBA - I INDUSTRIENS TJENESTE",
    "metaDescription": "ELBA - Din partner innen smøreteknikk i Norge. Fra den minste minigraver til Norges største produksjonsanlegg er vi klare til å møte utfordringen med deg."
  },
  {
    "id": "rørender",
    "title": "Rørender",
    "hero": {
      "src": "/images/produkter/08-3adcc4e8.jpg",
      "alt": "",
      "width": 400,
      "height": 265
    },
    "subnav": [
      "Rørender rette",
      "Rørender 90 grader",
      "Rørender 45 grader"
    ],
    "intro": [],
    "tables": [
      {
        "heading": "Forsinket stål (Zn-Ni)",
        "headers": [
          "D",
          "For Slange",
          "L",
          "L1",
          "SW",
          "Art.Nr."
        ],
        "rows": [
          [
            "4",
            "8.6",
            "51",
            "20",
            "10",
            "953146718"
          ],
          [
            "5",
            "8.6",
            "64",
            "30",
            "10",
            "100121218"
          ],
          [
            "6",
            "8.6",
            "51",
            "20",
            "10",
            "100121186"
          ],
          [
            "6",
            "8.6",
            "55",
            "24",
            "10",
            "100121190"
          ],
          [
            "6",
            "8.6",
            "61",
            "30",
            "10",
            "100121201"
          ],
          [
            "6",
            "8.6",
            "96.5",
            "65.5",
            "10",
            "953149589"
          ],
          [
            "8",
            "8.6",
            "61",
            "30",
            "10",
            "100121217"
          ],
          [
            "1/4\"",
            "8.6",
            "61",
            "30",
            "11",
            "953149590"
          ],
          [
            "3/16\"",
            "8.6",
            "51",
            "20",
            "10",
            "953148377"
          ],
          [
            "6",
            "11.2",
            "65.5",
            "22",
            "12",
            "953146736"
          ],
          [
            "8",
            "11.2",
            "65.5",
            "22",
            "12",
            "100121301"
          ],
          [
            "10",
            "11.2",
            "73.5",
            "30",
            "12",
            "953149591"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__rørender/02-64dfae38.jpg",
            "alt": "",
            "width": 594,
            "height": 344
          },
          {
            "src": "/images/produkter__rørender/03-13a29e6b.jpg",
            "alt": "",
            "width": 594,
            "height": 341
          }
        ]
      },
      {
        "heading": "Syrefast (316 / V4A)",
        "headers": [
          "D",
          "For Slange",
          "L",
          "L1",
          "SW",
          "Art.Nr."
        ],
        "rows": [
          [
            "6",
            "8.6",
            "61",
            "30",
            "10",
            "100121196"
          ],
          [
            "6",
            "11.2",
            "65.5",
            "22",
            "12",
            "953146814"
          ],
          [
            "8",
            "11.2",
            "65.5",
            "22",
            "12",
            "100121348"
          ],
          [
            "10",
            "11.2",
            "73.5",
            "30",
            "12",
            "953149592"
          ]
        ],
        "images": []
      },
      {
        "heading": "Forsinket stål (Zn-Ni)",
        "headers": [
          "D",
          "For Slange",
          "L",
          "L1",
          "SW",
          "Art.Nr."
        ],
        "rows": [
          [
            "6",
            "8.6",
            "51",
            "20",
            "10",
            "100121210"
          ],
          [
            "6",
            "8.6",
            "61",
            "30",
            "10",
            "953147621"
          ],
          [
            "1/4\"",
            "8.6",
            "61",
            "30",
            "11",
            "953149590"
          ],
          [
            "6",
            "11.2",
            "65.5",
            "22",
            "12",
            "953149351"
          ],
          [
            "1/4\"",
            "1/8\" x 5/16\"",
            "2.09\"",
            "1.18\"",
            "7/16\"",
            "953149595"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__rørender/04-50bf00d8.png",
            "alt": "",
            "width": 400,
            "height": 260
          },
          {
            "src": "/images/produkter__rørender/05-167b888a.png",
            "alt": "",
            "width": 400,
            "height": 260
          }
        ]
      },
      {
        "heading": "Syrefast (316 / V4A)",
        "headers": [
          "D",
          "For Slange",
          "L",
          "L1",
          "SW",
          "Art.Nr."
        ],
        "rows": [
          [
            "6",
            "8.6",
            "51",
            "20",
            "10",
            "953148849"
          ],
          [
            "1/4\"",
            "1/8\" x 5/16\"",
            "53",
            "21.5",
            "7/16\"",
            "953149596"
          ]
        ],
        "images": []
      },
      {
        "heading": "Forsinket (svart)",
        "headers": [
          "D",
          "For Slange",
          "L",
          "L1",
          "SW",
          "Art.Nr."
        ],
        "rows": [
          [
            "6",
            "8.6",
            "52.5",
            "21.5",
            "10",
            "953149593"
          ],
          [
            "6",
            "8.6",
            "61",
            "30",
            "10",
            "953149594"
          ]
        ],
        "images": []
      },
      {
        "heading": "Forsinket stål (Zn-Ni)",
        "headers": [
          "For Slange",
          "L",
          "L1",
          "SW",
          "Art.Nr."
        ],
        "rows": [
          [
            "8.6",
            "56",
            "25",
            "10",
            "953148677"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__rørender/06-ac720e8d.png",
            "alt": "",
            "width": 400,
            "height": 260
          },
          {
            "src": "/images/produkter__rørender/07-898b37e0.png",
            "alt": "",
            "width": 400,
            "height": 260
          }
        ]
      },
      {
        "heading": "Forsinket stål (Zn-Ni)",
        "headers": [
          "D",
          "For Slange",
          "L",
          "L1",
          "SW",
          "Art.Nr."
        ],
        "rows": [
          [
            "M 10x1",
            "8.6",
            "6 LL",
            "39",
            "11",
            "953147626"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__rørender/08-ea008481.png",
            "alt": "",
            "width": 400,
            "height": 260
          },
          {
            "src": "/images/produkter__rørender/09-5c81bee8.png",
            "alt": "",
            "width": 400,
            "height": 260
          }
        ]
      },
      {
        "heading": "Forsinket stål (Zn-Ni)",
        "headers": [
          "L",
          "For Slange",
          "G",
          "SW",
          "SW1",
          "Art.Nr."
        ],
        "rows": [
          [
            "56",
            "1/8\" x 5/16\"",
            "1/8 NPT",
            "\"7/16\"",
            "1/2\"",
            "953149598"
          ],
          [
            "57",
            "1/8\" x 5/16\"",
            "1/8 BSPT",
            "\"7/16\"",
            "1/2\"",
            "953149599"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__rørender/10-ff304097.png",
            "alt": "",
            "width": 400,
            "height": 260
          },
          {
            "src": "/images/produkter__rørender/11-4e10c600.png",
            "alt": "",
            "width": 400,
            "height": 260
          }
        ]
      },
      {
        "heading": "Forsinket stål (Zn-Ni)",
        "headers": [
          "G",
          "Hose Ø",
          "L",
          "SW",
          "SW1",
          "Art.Nr."
        ],
        "rows": [
          [
            "JIC37° 7/16",
            "8.6",
            "27.5",
            "14",
            "14",
            "953149600"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__rørender/12-21f1f3fb.png",
            "alt": "",
            "width": 400,
            "height": 260
          },
          {
            "src": "/images/produkter__rørender/13-bc424d9a.png",
            "alt": "",
            "width": 400,
            "height": 263
          }
        ]
      }
    ],
    "metaTitle": "ELBA - I INDUSTRIENS TJENESTE",
    "metaDescription": "ELBA - Din partner innen smøreteknikk i Norge. Fra den minste minigraver til Norges største produksjonsanlegg er vi klare til å møte utfordringen med deg."
  },
  {
    "id": "skottgjennomføring",
    "title": "Skottgjennomføring",
    "hero": {
      "src": "/images/produkter/06-53f273f5.jpg",
      "alt": "",
      "width": 400,
      "height": 260
    },
    "subnav": [
      "Skottgjennomføring",
      "Skottgjennomføring innv. gjenger",
      "Skottgjennomføring 90 grader"
    ],
    "intro": [],
    "tables": [
      {
        "heading": "Forsinket stål (Zn-Ni)",
        "headers": [
          "D",
          "Serie",
          "SW",
          "SW1",
          "L",
          "Art.Nr."
        ],
        "rows": [
          [
            "4",
            "LL",
            "",
            "10",
            "",
            "11643140"
          ],
          [
            "6",
            "L",
            "17",
            "14",
            "48",
            "0401 4701 006"
          ],
          [
            "8",
            "L",
            "19",
            "17",
            "49",
            "0401 4701 106"
          ],
          [
            "10",
            "L",
            "22",
            "19",
            "52",
            "953149560"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__skottgjennomføring/02-b6a4b506.png",
            "alt": "",
            "width": 400,
            "height": 260
          },
          {
            "src": "/images/produkter__skottgjennomføring/03-e2bc3bf0.png",
            "alt": "",
            "width": 400,
            "height": 260
          }
        ]
      },
      {
        "heading": "Syrefast (316 / V4A)",
        "headers": [
          "D",
          "Serie",
          "SW",
          "SW1",
          "L",
          "Art.Nr."
        ],
        "rows": [
          [
            "6",
            "L",
            "17",
            "14",
            "48",
            "0401 4701 013"
          ],
          [
            "8",
            "L",
            "19",
            "17",
            "49",
            "0401 4701 113"
          ]
        ],
        "images": []
      }
    ],
    "metaTitle": "ELBA - I INDUSTRIENS TJENESTE",
    "metaDescription": "ELBA - Din partner innen smøreteknikk i Norge. Fra den minste minigraver til Norges største produksjonsanlegg er vi klare til å møte utfordringen med deg."
  },
  {
    "id": "skruhylser",
    "title": "Skruhylser",
    "hero": {
      "src": "/images/produkter/04-b584c29f.jpg",
      "alt": "",
      "width": 400,
      "height": 260
    },
    "subnav": [],
    "intro": [],
    "tables": [
      {
        "heading": "For slange Ø 8,6",
        "headers": [
          "L",
          "SW",
          "Art.Nr",
          "Material"
        ],
        "rows": [
          [
            "28",
            "12",
            "100121200",
            "Forsinket blank"
          ],
          [
            "28",
            "12",
            "953149585",
            "Forsinket sort"
          ],
          [
            "28",
            "12",
            "100121197",
            "Syrefast"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__skruhylser/02-5962d532.png",
            "alt": "",
            "width": 400,
            "height": 260
          },
          {
            "src": "/images/produkter__rørender/03-13a29e6b.jpg",
            "alt": "",
            "width": 594,
            "height": 341
          },
          {
            "src": "/images/produkter__skruhylser/04-8a3d91d2.png",
            "alt": "",
            "width": 400,
            "height": 260
          }
        ]
      },
      {
        "heading": "For slange Ø 11,2",
        "headers": [
          "L",
          "SW",
          "Art.Nr",
          "Material"
        ],
        "rows": [
          [
            "28",
            "12",
            "100121305",
            "Forsinket blank"
          ],
          [
            "28",
            "12",
            "953149586",
            "Forsinket sort"
          ],
          [
            "28",
            "12",
            "100121347",
            "Syrefast"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__skruhylser/05-83345125.png",
            "alt": "",
            "width": 400,
            "height": 260
          },
          {
            "src": "/images/produkter__skruhylser/06-0aee6c47.png",
            "alt": "",
            "width": 400,
            "height": 260
          }
        ]
      },
      {
        "heading": "For slange Ø 5/16\"",
        "headers": [
          "L",
          "SW",
          "Art.Nr",
          "Material"
        ],
        "rows": [
          [
            "26",
            "1/2\"",
            "953149587",
            "Forsinket blank"
          ],
          [
            "26",
            "1/2\"",
            "953149588",
            "Syrefast"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__skruhylser/07-13136f12.png",
            "alt": "",
            "width": 400,
            "height": 260
          },
          {
            "src": "/images/produkter__skruhylser/08-aba8a421.png",
            "alt": "",
            "width": 400,
            "height": 260
          }
        ]
      }
    ],
    "metaTitle": "ELBA - I INDUSTRIENS TJENESTE",
    "metaDescription": "ELBA - Din partner innen smøreteknikk i Norge. Fra den minste minigraver til Norges største produksjonsanlegg er vi klare til å møte utfordringen med deg."
  },
  {
    "id": "slanger",
    "title": "Slanger",
    "hero": {
      "src": "/images/produkter/07-9bd24da2.jpg",
      "alt": "",
      "width": 1440,
      "height": 432
    },
    "subnav": [
      "Høytrykkslange",
      "Nylonrør"
    ],
    "intro": [],
    "tables": [
      {
        "heading": null,
        "headers": [
          "D",
          "D1",
          "Fett",
          "Art.Nr."
        ],
        "rows": [
          [
            "8.6",
            "4",
            "NLGI 2",
            "100120200"
          ],
          [
            "8.6",
            "4",
            "tom",
            "100120201"
          ],
          [
            "11.3",
            "6.3",
            "NLGI 2",
            "100120265"
          ],
          [
            "11.3",
            "6.3",
            "tom",
            "100120266"
          ],
          [
            "5/16\"",
            "1/8\"",
            "tom",
            "på forespørsel"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__slanger/02-350b79a1.png",
            "alt": "",
            "width": 400,
            "height": 260
          },
          {
            "src": "/images/produkter__slanger/03-994707cc.png",
            "alt": "",
            "width": 400,
            "height": 260
          }
        ]
      }
    ],
    "metaTitle": "ELBA - I INDUSTRIENS TJENESTE",
    "metaDescription": "ELBA - Din partner innen smøreteknikk i Norge. Fra den minste minigraver til Norges største produksjonsanlegg er vi klare til å møte utfordringen med deg."
  },
  {
    "id": "snittringmatur",
    "title": "Snittringmatur",
    "hero": {
      "src": "/images/produkter/11-575445e6.jpg",
      "alt": "",
      "width": 400,
      "height": 257
    },
    "subnav": [
      "Vinkel \"WE\"",
      "Rett \"GE\"",
      "Sammenkobling \"G\"",
      "Sammenkobling \"W\"",
      "T-stykke",
      "Muttere",
      "Snittringer"
    ],
    "intro": [],
    "tables": [
      {
        "heading": "Forsinket stål (Zn-Ni)",
        "headers": [
          "RøR Dim. D",
          "Gjenge D1",
          "Serie",
          "Type",
          "Art.Nr"
        ],
        "rows": [
          [
            "4",
            "M6 x 1",
            "LL",
            "WE 4 LL M6X1 ZN",
            "11643050"
          ],
          [
            "4",
            "M8 x 1",
            "LL",
            "WE 4 LL M8X1 ZN",
            "11643060"
          ],
          [
            "4",
            "M8 x 1.25",
            "LL",
            "WE 4 LL M8X1.25 ZN",
            "11643065"
          ],
          [
            "4",
            "M10 x 1",
            "LL",
            "WE 4 LL M10X1 ZN",
            "04012210406"
          ],
          [
            "4",
            "R 1/8",
            "LL",
            "WE 4 LLR 1/8\" ZN",
            "11643070"
          ],
          [
            "5",
            "M6 x 1",
            "LL",
            "WE 5 LL M6X1 ZN",
            "953147779"
          ],
          [
            "5",
            "M8 x 1",
            "LL",
            "WE 5 LL M8X1 ZN",
            "953147863"
          ],
          [
            "5",
            "R 1/8",
            "LL",
            "We 5LLR 1/8\" ZN",
            "953147799"
          ],
          [
            "6",
            "M6 x 1",
            "LL",
            "WE 6 LL M6X1 ZN",
            "04012200406"
          ],
          [
            "6",
            "M8 x 1.25",
            "LL",
            "WE 6 LL M8X1.25 ZN",
            "11643089"
          ],
          [
            "6",
            "M8 x 1",
            "LL",
            "WE 6 LL M8X1 ZN",
            "04012200506"
          ],
          [
            "6",
            "M10 x 1",
            "LL",
            "WE 6 LL M10X1 ZN",
            "0401 2200 306"
          ],
          [
            "6",
            "R 1/8",
            "LL",
            "WE 6 LLR 1/8\"ZN",
            "04012200606"
          ],
          [
            "6",
            "1/8 NPT",
            "LL",
            "WE 6 LLR 1/8\"NPT ZN",
            "953149541"
          ],
          [
            "6",
            "M10 x 1",
            "L",
            "WE 6 L M10X1 ZN",
            "04012201006"
          ],
          [
            "6",
            "R 1/8",
            "L",
            "WE 6 LR 1/8\"ZN",
            "953146776"
          ],
          [
            "6",
            "R 1/4",
            "L",
            "WE 6 LR 1/4\"ZN",
            "953147710"
          ],
          [
            "6",
            "R 1/4",
            "S",
            "WE 6 S 1/4\" ZN",
            "106069"
          ],
          [
            "6",
            "1/4-28 UNF",
            "LL",
            "WE 6 LL 1/4-28 UNF ZN",
            "953149540"
          ],
          [
            "8",
            "M10 x 1",
            "LL",
            "WE 8 LLR M10X1 ZN",
            "953147932"
          ],
          [
            "8",
            "R 1/8",
            "LL",
            "WE 8 LLR 1/8\" ZN",
            "11643090"
          ],
          [
            "8",
            "R 1/4",
            "L",
            "WE 8 LR 1/4\"ZN",
            "116024"
          ],
          [
            "10",
            "R 1/4",
            "L",
            "WE 10 LR 1/4\"ZN",
            "på forespørsel"
          ]
        ],
        "images": [
          {
            "src": "/images/produkter__snittringmatur/02-62732d8a.png",
            "alt": "",
            "width": 400,
            "height": 260
          },
          {
            "src": "/images/produkter__snittringmatur/03-bd137810.png",
            "alt": "",
            "width": 400,
            "height": 260
          }
        ]
      },
      {
        "heading": "Syrefast (316 / V4A)",
        "headers": [
          "RøR Dim. D",
          "Gjenge D1",
          "Serie",
          "Type",
          "Art.Nr"
        ],
        "rows": [
          [
            "4",
            "M6 x 1",
            "LL",
            "WE 4 LL M6X1 SS",
            "953148859"
          ],
          [
            "4",
            "M8 x 1",
            "LL",
            "WE 4 LL M8X1 SS",
            "04012210513"
          ],
          [
            "4",
            "M10 x 1",
            "LL",
            "WE 4 LL M10X1 SS",
            "953148860"
          ],
          [
            "4",
            "R 1/8",
            "LL",
            "WE 4 LLR 1/8\" SS",
            "04012210613"
          ],
          [
            "6",
            "M6 x 1",
            "LL",
            "WE 6 LL M6X1 SS",
            "106057"
          ],
          [
            "6",
            "M8 x 1",
            "LL",
            "WE 6 LL M8X1 SS",
            "106038"
          ],
          [
            "6",
            "M10 x 1",
            "LL",
            "WE 6 LL M10X1 SS",
            "04012200313LL"
          ],
          [
            "6",
            "R 1/8",
            "LL",
            "WE 6 LLR 1/8\"SS",
            "12805740"
          ],
          [
            "6",
            "R 1/4",
            "L",
            "WE 6 LR 1/8\" SS",
            "12805760"
          ],
          [
            "6",
            "R 1/4",
            "S",
            "WE 6 S 1/4\" SS",
            "1060109"
          ],
          [
            "8",
            "R 1/8",
            "L",
            "WE 8 LR 1/8\" SS",
            "11643302"
          ],
          [
            "10",
            "R 1/8",
            "L",
            "WE 10 LR 1/8\" SS",
            "953147089"
          ]
        ],
        "images": []
      }
    ],
    "metaTitle": "ELBA - I INDUSTRIENS TJENESTE",
    "metaDescription": "ELBA - Din partner innen smøreteknikk i Norge. Fra den minste minigraver til Norges største produksjonsanlegg er vi klare til å møte utfordringen med deg."
  }
];

export const productBySlug = (slug: string): Product | undefined => produkter.find((p) => p.id === slug);
